# Generated by Django 4.0.3 on 2022-04-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriya'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Tovar', 'verbose_name_plural': 'Tovarlar'},
        ),
        migrations.AddField(
            model_name='product',
            name='tel_raqam',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
